<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Platforms>AnyCPU;x64</Platforms>
    <StartupObject>Fighter2D.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Assets\backgrounds\menu.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\backgrounds\player_select_bg.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\data\fighting_moves.hor">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\data\movement_moves.hor">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\data\moves.hor">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\data\maps.hor">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\fonts\Born2bSporty\Born2bSporty.fnt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\fonts\Born2bSporty\Born2bSporty.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\fonts\FIGHTERFISH\FIGHTERFISH.fnt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\fonts\FIGHTERFISH\FIGHTERFISH.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\dungeon.tmx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\japan.tmx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\Background.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\Background.tsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\Background_albedo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\Basic-sample.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\Basic.tiled-project">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\Basic.tiled-session">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\oak_woods.tsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\oak_woods_tileset.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\oak_woods_tileset_albedo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\Platform-and-Objects.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\Platform-and-Objects.tsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\Platform-and-Objects_albedo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\Sky.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\Sky.tsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\maps\tilesets\Sky_albedo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\sprites\player\definition.hor">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\sprites\player\spritesheet.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\sprites\player\_spritesheet.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\ui\bar.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\ui\overlay.hor">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\ui\logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\fonts\" />
    <Folder Include="Assets\sprites\bar\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\horizon\Bogz.Logging\Bogz.Logging.csproj" />
    <ProjectReference Include="..\horizon\Horizon.Content\Horizon.Content.csproj" />
    <ProjectReference Include="..\horizon\Horizon.Core\Horizon.Core.csproj" />
    <ProjectReference Include="..\horizon\Horizon.Engine\Horizon.Engine.csproj" />
    <ProjectReference Include="..\horizon\Horizon.Horlang\Horizon.HIDL.csproj" />
    <ProjectReference Include="..\horizon\Horizon.Input\Horizon.Input.csproj" />
    <ProjectReference Include="..\horizon\Horizon.OpenGL\Horizon.OpenGL.csproj" />
    <ProjectReference Include="..\horizon\Horizon.Physics\Horizon.Physics.csproj" />
    <ProjectReference Include="..\horizon\Horizon.Rendering\Horizon.Rendering.csproj" />
    <ProjectReference Include="..\horizon\Horizon.Webhost\Horizon.Webhost.csproj" />
  </ItemGroup>

</Project>
